### ISSUE TITLE
 Expected string for argument 'padding' not ListWrapper([ListWrapper([0, 0]), ListWrapper([1, 0]), ListWrapper([0, 2]), ListWrapper([0, 0])]).

### ISSUE THREAD

**Issue by yudashuixiao1** [zqlsnr/SKIP-DPCRN-Base-Tflite-And-Onnx#2]
How to deal with this ppoblem,thanks!

my environment: tf==2.3.0 rtx3090

**Comment by zqlsnr** [comment]
Sorry, it took so long to reply to you. You can add tf.pad before two-dimensional convolution, and two-dimensional convolution calculates the matrix shape after tf.pad.

**Comment by yudashuixiao1** [comment]
> Sorry, it took so long to reply to you. You can add tf.pad before two-dimensional convolution, and two-dimensional convolution calculates the matrix shape after tf.pad.

thank you very much ，it works!
